name: Regenerate Lock File and Deploy

on:
  push:
    branches: [main]

jobs:
  regenerate-lock-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Regenerate Lock File
        run: |
          npm install
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Regenerate package-lock.json"
          git push

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
