name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 3: Regenerate the lock file (force `package-lock.json` creation)
      - name: Force regenerate package-lock.json
        run: |
          rm -f package-lock.json
          npm install
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Regenerate package-lock.json" || true
          git push || true

      # Step 4: Build the project
      - name: Build Project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
