name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps @radix-ui/react-arrow@1.0.0 @radix-ui/react-context@1.0.0 @radix-ui/react-dropdown-menu@2.0.6 @radix-ui/react-use-rect@1.0.0 @radix-ui/react-use-size@1.0.0 @radix-ui/react-slot@1.0.0 @floating-ui/dom@1.6.1 @floating-ui/core@1.6.0 @floating-ui/utils@0.2.1 @radix-ui/react-context@1.0.0 tslib@2.6.1 clsx@1.2 @emotion/is-prop-valid@0.8 @emotion/memoize@0.7.4 react-remove-scroll-bar@2.3.6 react-style-singleton@2.2.1 use-callback-ref@1.3.2 use-sidecar@1.3.2 get-nonce@1.0.1 invariant@2.2.4 detect-node-es@1.0

      - name: Build
        run: |
          npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
