name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 3: Debugging and Environment Info
      - name: Display Environment Info
        run: |
          node -v
          npm -v
          ls -al
          npm config list

      # Step 4: Install Dependencies and Generate Lock File
      - name: Install dependencies and create package-lock.json
        run: |
          npm install --legacy-peer-deps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package-lock.json || true
          git commit -m "Add package-lock.json" || true
          git push || true

      # Step 5: Build the Project
      - name: Build Project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
